#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
if [ -e "~/.Xmodmap" ] ; then
    xmodmap "~/.Xmodmap"
fi

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.

# Checks if a command is already running, then if not and the command is available on
# the system it will start it in the background.
# 1: Command to check for, look for, and run
# 2+: Options to pass to the command if/when run
check_and_start()
{
    cmd=$1
    shift
    if [ -z "$(pidof ${cmd})" ] && command -v ${cmd} &>/dev/null ; then
        ${cmd} $* &
    fi
}

# Enable this via the fbautostart method instead if wanted
## Allow gnome related things
#check_and_start gnome-settings-daemon

# Keep nautilus running in the background to automate things
# like USB hotplug and whatnot
check_and_start nautilus -n --no-desktop

# If we are in VMWare, we have to manually run this tool for the integration to work properly
check_and_start vmware-user-suid-wrapper

# Systray icon for network management, autostart doesn't start it properly
check_and_start nm-applet

# Run this to set the background to the last thing fluxbox configured it to
if [ -e "~/.fluxbox/lastwallpaper" ] ; then
    fbsetbg -l
fi

########################################################################

# All changes that shouldn't be shared among everyone should be
# placed in this file, creating it if necessary
if [ -e ~/.fluxbox/custom-startup ] ; then
    ~/.fluxbox/custom-startup
fi

#########################################################################

# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
# This is modified by the Ubuntu provided startup tool via gnome-session-properties
#
# The files we look for are in ~/.config/fluxbox-autostart and
# gnome-session-properties modifies the ones in ~/.config/autostart.
# Symlink the ones you want enabled into ~/.config/fluxbox-autostart/autostart
# This will also start everything in /etc/xdg/autostart/, which is where
# Unity and other launchers store their system GUI startup files.  You may
# need to hand modify the files there to add FLUXBOX to OnlyShowIn and NotShowIn lists, eg:
#  OnlyShowIn=Unity;FLUXBOX;
#  NotShowIn=GNOME;Unity:FLUXBOX;
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    XDG_CONFIG_HOME=~/.config/fluxbox-autostart/ fbautostart &
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

#exec fluxbox
# or if you want to keep a log:
exec fluxbox -log "/home/${USER}/fluxbox_log"
